//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AxoneMFGRJ.APITicket {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://www.axoneinfotech.com/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ClinetTicket_JSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClinetTicket_JSON_V1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ClientTicket_DatasetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::AxoneMFGRJ.Properties.Settings.Default.AxoneMFGRJ_APITicket_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ClinetTicket_JSONCompletedEventHandler ClinetTicket_JSONCompleted;
        
        /// <remarks/>
        public event ClinetTicket_JSON_V1CompletedEventHandler ClinetTicket_JSON_V1Completed;
        
        /// <remarks/>
        public event ClientTicket_DatasetCompletedEventHandler ClientTicket_DatasetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axoneinfotech.com/ClinetTicket_JSON", RequestNamespace="http://www.axoneinfotech.com/", ResponseNamespace="http://www.axoneinfotech.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClinetTicket_JSON(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP) {
            object[] results = this.Invoke("ClinetTicket_JSON", new object[] {
                        pStrTicketNoStr,
                        pStrTicketNo,
                        pIntClient_ID,
                        pStrProjectName,
                        pStrTicketGeneratedBy,
                        pStrTicketDate,
                        pStrExpetedFinishDate,
                        pStrTaskDetail,
                        pStrPriority,
                        pStrTicketStatus,
                        pStrEntryIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ClinetTicket_JSONAsync(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP) {
            this.ClinetTicket_JSONAsync(pStrTicketNoStr, pStrTicketNo, pIntClient_ID, pStrProjectName, pStrTicketGeneratedBy, pStrTicketDate, pStrExpetedFinishDate, pStrTaskDetail, pStrPriority, pStrTicketStatus, pStrEntryIP, null);
        }
        
        /// <remarks/>
        public void ClinetTicket_JSONAsync(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP, object userState) {
            if ((this.ClinetTicket_JSONOperationCompleted == null)) {
                this.ClinetTicket_JSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClinetTicket_JSONOperationCompleted);
            }
            this.InvokeAsync("ClinetTicket_JSON", new object[] {
                        pStrTicketNoStr,
                        pStrTicketNo,
                        pIntClient_ID,
                        pStrProjectName,
                        pStrTicketGeneratedBy,
                        pStrTicketDate,
                        pStrExpetedFinishDate,
                        pStrTaskDetail,
                        pStrPriority,
                        pStrTicketStatus,
                        pStrEntryIP}, this.ClinetTicket_JSONOperationCompleted, userState);
        }
        
        private void OnClinetTicket_JSONOperationCompleted(object arg) {
            if ((this.ClinetTicket_JSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClinetTicket_JSONCompleted(this, new ClinetTicket_JSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axoneinfotech.com/ClinetTicket_JSON_V1", RequestNamespace="http://www.axoneinfotech.com/", ResponseNamespace="http://www.axoneinfotech.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClinetTicket_JSON_V1(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP) {
            object[] results = this.Invoke("ClinetTicket_JSON_V1", new object[] {
                        pStrTicketNoStr,
                        pStrTicketNo,
                        pIntClient_ID,
                        pStrProjectName,
                        pStrTicketGeneratedBy,
                        pStrTicketDate,
                        pStrExpetedFinishDate,
                        pStrTaskDetail,
                        pStrPriority,
                        pStrTicketStatus,
                        pStrEntryIP});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClinetTicket_JSON_V1Async(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP) {
            this.ClinetTicket_JSON_V1Async(pStrTicketNoStr, pStrTicketNo, pIntClient_ID, pStrProjectName, pStrTicketGeneratedBy, pStrTicketDate, pStrExpetedFinishDate, pStrTaskDetail, pStrPriority, pStrTicketStatus, pStrEntryIP, null);
        }
        
        /// <remarks/>
        public void ClinetTicket_JSON_V1Async(string pStrTicketNoStr, int pStrTicketNo, long pIntClient_ID, string pStrProjectName, string pStrTicketGeneratedBy, string pStrTicketDate, string pStrExpetedFinishDate, string pStrTaskDetail, string pStrPriority, string pStrTicketStatus, string pStrEntryIP, object userState) {
            if ((this.ClinetTicket_JSON_V1OperationCompleted == null)) {
                this.ClinetTicket_JSON_V1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnClinetTicket_JSON_V1OperationCompleted);
            }
            this.InvokeAsync("ClinetTicket_JSON_V1", new object[] {
                        pStrTicketNoStr,
                        pStrTicketNo,
                        pIntClient_ID,
                        pStrProjectName,
                        pStrTicketGeneratedBy,
                        pStrTicketDate,
                        pStrExpetedFinishDate,
                        pStrTaskDetail,
                        pStrPriority,
                        pStrTicketStatus,
                        pStrEntryIP}, this.ClinetTicket_JSON_V1OperationCompleted, userState);
        }
        
        private void OnClinetTicket_JSON_V1OperationCompleted(object arg) {
            if ((this.ClinetTicket_JSON_V1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClinetTicket_JSON_V1Completed(this, new ClinetTicket_JSON_V1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axoneinfotech.com/ClientTicket_Dataset", RequestNamespace="http://www.axoneinfotech.com/", ResponseNamespace="http://www.axoneinfotech.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClientTicket_Dataset(string pStrTicketNo, string pStrFromDate, string pStrToDate, string pStrStatus) {
            object[] results = this.Invoke("ClientTicket_Dataset", new object[] {
                        pStrTicketNo,
                        pStrFromDate,
                        pStrToDate,
                        pStrStatus});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClientTicket_DatasetAsync(string pStrTicketNo, string pStrFromDate, string pStrToDate, string pStrStatus) {
            this.ClientTicket_DatasetAsync(pStrTicketNo, pStrFromDate, pStrToDate, pStrStatus, null);
        }
        
        /// <remarks/>
        public void ClientTicket_DatasetAsync(string pStrTicketNo, string pStrFromDate, string pStrToDate, string pStrStatus, object userState) {
            if ((this.ClientTicket_DatasetOperationCompleted == null)) {
                this.ClientTicket_DatasetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClientTicket_DatasetOperationCompleted);
            }
            this.InvokeAsync("ClientTicket_Dataset", new object[] {
                        pStrTicketNo,
                        pStrFromDate,
                        pStrToDate,
                        pStrStatus}, this.ClientTicket_DatasetOperationCompleted, userState);
        }
        
        private void OnClientTicket_DatasetOperationCompleted(object arg) {
            if ((this.ClientTicket_DatasetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClientTicket_DatasetCompleted(this, new ClientTicket_DatasetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ClinetTicket_JSONCompletedEventHandler(object sender, ClinetTicket_JSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClinetTicket_JSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClinetTicket_JSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ClinetTicket_JSON_V1CompletedEventHandler(object sender, ClinetTicket_JSON_V1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClinetTicket_JSON_V1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClinetTicket_JSON_V1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ClientTicket_DatasetCompletedEventHandler(object sender, ClientTicket_DatasetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClientTicket_DatasetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClientTicket_DatasetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591