//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxoneMFGRJ.FileUploadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iJiya.com/", ConfigurationName="FileUploadService.FileUploaderSoap")]
    public interface FileUploaderSoap {
        
        // CODEGEN: Generating message contract since element name pByte from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/UploadFile", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.UploadFileResponse UploadFile(AxoneMFGRJ.FileUploadService.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name pByte from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/UploadFileToSpecificFolder", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderResponse UploadFileToSpecificFolder(AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequest request);
        
        // CODEGEN: Generating message contract since element name pStrFileName from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/GetFile", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.GetFileResponse GetFile(AxoneMFGRJ.FileUploadService.GetFileRequest request);
        
        // CODEGEN: Generating message contract since element name pStrFolder from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/GetFileFromSpecificFolder", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderResponse GetFileFromSpecificFolder(AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequest request);
        
        // CODEGEN: Generating message contract since element name pStrFileName from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/DeleteFile", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.DeleteFileResponse DeleteFile(AxoneMFGRJ.FileUploadService.DeleteFileRequest request);
        
        // CODEGEN: Generating message contract since element name pStrFolder from namespace http://www.iJiya.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iJiya.com/DeleteFileFromSpecificFolder", ReplyAction="*")]
        AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderResponse DeleteFileFromSpecificFolder(AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(AxoneMFGRJ.FileUploadService.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] pByte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pStrFileName;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] pByte, string pStrFileName) {
            this.pByte = pByte;
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(AxoneMFGRJ.FileUploadService.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToSpecificFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToSpecificFolder", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequestBody Body;
        
        public UploadFileToSpecificFolderRequest() {
        }
        
        public UploadFileToSpecificFolderRequest(AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class UploadFileToSpecificFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] pByte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pStrFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pStrFileName;
        
        public UploadFileToSpecificFolderRequestBody() {
        }
        
        public UploadFileToSpecificFolderRequestBody(byte[] pByte, string pStrFolder, string pStrFileName) {
            this.pByte = pByte;
            this.pStrFolder = pStrFolder;
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToSpecificFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToSpecificFolderResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderResponseBody Body;
        
        public UploadFileToSpecificFolderResponse() {
        }
        
        public UploadFileToSpecificFolderResponse(AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class UploadFileToSpecificFolderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileToSpecificFolderResult;
        
        public UploadFileToSpecificFolderResponseBody() {
        }
        
        public UploadFileToSpecificFolderResponseBody(string UploadFileToSpecificFolderResult) {
            this.UploadFileToSpecificFolderResult = UploadFileToSpecificFolderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(AxoneMFGRJ.FileUploadService.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pStrFileName;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string pStrFileName) {
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(AxoneMFGRJ.FileUploadService.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileFromSpecificFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileFromSpecificFolder", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequestBody Body;
        
        public GetFileFromSpecificFolderRequest() {
        }
        
        public GetFileFromSpecificFolderRequest(AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class GetFileFromSpecificFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pStrFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pStrFileName;
        
        public GetFileFromSpecificFolderRequestBody() {
        }
        
        public GetFileFromSpecificFolderRequestBody(string pStrFolder, string pStrFileName) {
            this.pStrFolder = pStrFolder;
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileFromSpecificFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileFromSpecificFolderResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderResponseBody Body;
        
        public GetFileFromSpecificFolderResponse() {
        }
        
        public GetFileFromSpecificFolderResponse(AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class GetFileFromSpecificFolderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileFromSpecificFolderResult;
        
        public GetFileFromSpecificFolderResponseBody() {
        }
        
        public GetFileFromSpecificFolderResponseBody(byte[] GetFileFromSpecificFolderResult) {
            this.GetFileFromSpecificFolderResult = GetFileFromSpecificFolderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFile", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.DeleteFileRequestBody Body;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(AxoneMFGRJ.FileUploadService.DeleteFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class DeleteFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pStrFileName;
        
        public DeleteFileRequestBody() {
        }
        
        public DeleteFileRequestBody(string pStrFileName) {
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.DeleteFileResponseBody Body;
        
        public DeleteFileResponse() {
        }
        
        public DeleteFileResponse(AxoneMFGRJ.FileUploadService.DeleteFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class DeleteFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileResult;
        
        public DeleteFileResponseBody() {
        }
        
        public DeleteFileResponseBody(string DeleteFileResult) {
            this.DeleteFileResult = DeleteFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileFromSpecificFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileFromSpecificFolder", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequestBody Body;
        
        public DeleteFileFromSpecificFolderRequest() {
        }
        
        public DeleteFileFromSpecificFolderRequest(AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class DeleteFileFromSpecificFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pStrFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pStrFileName;
        
        public DeleteFileFromSpecificFolderRequestBody() {
        }
        
        public DeleteFileFromSpecificFolderRequestBody(string pStrFolder, string pStrFileName) {
            this.pStrFolder = pStrFolder;
            this.pStrFileName = pStrFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileFromSpecificFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileFromSpecificFolderResponse", Namespace="http://www.iJiya.com/", Order=0)]
        public AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderResponseBody Body;
        
        public DeleteFileFromSpecificFolderResponse() {
        }
        
        public DeleteFileFromSpecificFolderResponse(AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iJiya.com/")]
    public partial class DeleteFileFromSpecificFolderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileFromSpecificFolderResult;
        
        public DeleteFileFromSpecificFolderResponseBody() {
        }
        
        public DeleteFileFromSpecificFolderResponseBody(string DeleteFileFromSpecificFolderResult) {
            this.DeleteFileFromSpecificFolderResult = DeleteFileFromSpecificFolderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileUploaderSoapChannel : AxoneMFGRJ.FileUploadService.FileUploaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileUploaderSoapClient : System.ServiceModel.ClientBase<AxoneMFGRJ.FileUploadService.FileUploaderSoap>, AxoneMFGRJ.FileUploadService.FileUploaderSoap {
        
        public FileUploaderSoapClient() {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.UploadFileResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.UploadFile(AxoneMFGRJ.FileUploadService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] pByte, string pStrFileName) {
            AxoneMFGRJ.FileUploadService.UploadFileRequest inValue = new AxoneMFGRJ.FileUploadService.UploadFileRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.UploadFileRequestBody();
            inValue.Body.pByte = pByte;
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.UploadFileResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.UploadFileToSpecificFolder(AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequest request) {
            return base.Channel.UploadFileToSpecificFolder(request);
        }
        
        public string UploadFileToSpecificFolder(byte[] pByte, string pStrFolder, string pStrFileName) {
            AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequest inValue = new AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderRequestBody();
            inValue.Body.pByte = pByte;
            inValue.Body.pStrFolder = pStrFolder;
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.UploadFileToSpecificFolderResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).UploadFileToSpecificFolder(inValue);
            return retVal.Body.UploadFileToSpecificFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.GetFileResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.GetFile(AxoneMFGRJ.FileUploadService.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string pStrFileName) {
            AxoneMFGRJ.FileUploadService.GetFileRequest inValue = new AxoneMFGRJ.FileUploadService.GetFileRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.GetFileRequestBody();
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.GetFileResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.GetFileFromSpecificFolder(AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequest request) {
            return base.Channel.GetFileFromSpecificFolder(request);
        }
        
        public byte[] GetFileFromSpecificFolder(string pStrFolder, string pStrFileName) {
            AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequest inValue = new AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderRequestBody();
            inValue.Body.pStrFolder = pStrFolder;
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.GetFileFromSpecificFolderResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).GetFileFromSpecificFolder(inValue);
            return retVal.Body.GetFileFromSpecificFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.DeleteFileResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.DeleteFile(AxoneMFGRJ.FileUploadService.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public string DeleteFile(string pStrFileName) {
            AxoneMFGRJ.FileUploadService.DeleteFileRequest inValue = new AxoneMFGRJ.FileUploadService.DeleteFileRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.DeleteFileRequestBody();
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.DeleteFileResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).DeleteFile(inValue);
            return retVal.Body.DeleteFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderResponse AxoneMFGRJ.FileUploadService.FileUploaderSoap.DeleteFileFromSpecificFolder(AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequest request) {
            return base.Channel.DeleteFileFromSpecificFolder(request);
        }
        
        public string DeleteFileFromSpecificFolder(string pStrFolder, string pStrFileName) {
            AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequest inValue = new AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequest();
            inValue.Body = new AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderRequestBody();
            inValue.Body.pStrFolder = pStrFolder;
            inValue.Body.pStrFileName = pStrFileName;
            AxoneMFGRJ.FileUploadService.DeleteFileFromSpecificFolderResponse retVal = ((AxoneMFGRJ.FileUploadService.FileUploaderSoap)(this)).DeleteFileFromSpecificFolder(inValue);
            return retVal.Body.DeleteFileFromSpecificFolderResult;
        }
    }
}
